config/routes.rb
Gyst::Application.routes.draw do

  devise_for :users

resources :goal_sets do
  resources :goals 
end

match "toggle_complete/:id" =>"goal_sets#toggle_complete"
match "destroy_goal/:id" =>"goal_sets#destroy_goal"
match "add_goal/:id" =>"goal_sets#add_goal"
match "destroy_all_goalsets" =>"goal_sets#destroy_all_goalsets"
root to: 'goal_sets#index'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
	attr_accessible :complete, :content
	belongs_to :goal_set
	default_scope :order=> 'created_at'
	scope :complete, where(:complete => true)
end

app/models/goal_set.rb
class GoalSet < ActiveRecord::Base
  has_many :goals,:dependent => :delete_all
  attr_accessible :start_time, :daily, :goals_attributes
  accepts_nested_attributes_for :goals, 
  	:allow_destroy => true, :reject_if => :all_blank
  validates :start_time, :uniqueness=>true

  def completed_goals
  	goals.complete.count
  end

  def start_time_readable
  	if start_time.to_date == Date.today
  		"Today"
  	else
  		start_time.strftime("%A")
  	end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/goal_sets_controller.rb
class GoalSetsController < ApplicationController
	include GoalsHelper
	before_filter :authenticate_user!, :load, :only => [:index]

	def load
		@goalsets = GoalSet.all
		@total_goal_count = Goal.count
		@completed_goal_count = Goal.complete.count
		@current_goalsets = GoalSet.all(:conditions=>["created_at >=:start_time", {:start_time=>Date.yesterday}])

		@goalset = GoalSet.new
	end

	def index
	end

	def edit
		@goalset = GoalSet.find(params[:id])
	end

	def destroy
		@goalset = GoalSet.find(params[:id])

		if @goalset.destroy
			flash[:notice] = "Successfully destroyed GoalSet."
			load	
		end
	end

	def create
		@goalset = GoalSet.new(params[:goalset])
		
		if @goalset.save
			flash[:notice] = "Successfully created GoalSet."
			load
		end
	end

	def update
		@goalset = GoalSet.find(params[:id])
		
		if @goalset.update_attributes params[:goalset] 
			flash[:notice] = "Successfully updated Goals"
			load
		end
	end

	def toggle_complete
		@goal = Goal.find(params[:id])
		@goal.toggle!(:complete)
		load
	end

	def destroy_goal
		@goal = Goal.find(params[:id])
		@goal.destroy
		load
	end

	def destroy_all_goalsets
		GoalSet.destroy_all
		load
	end

	def add_goal
		@goalset = GoalSet.find(params[:id])
		@goalset.goals.build
	end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	include GoalsHelper

	def index
	end

	def new
	end

	def create
	end

	def edit
	end

	def update	
	end

	def destroy
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goal_set_helper.rb
module GoalSetHelper
end

app/helpers/goals_helper.rb
module GoalsHelper

	def goals_complete_percentage(goals_complete, goals_total)
		unless goals_total == 0 
			goals_complete.to_f / goals_total.to_f * 100
		end
	end

	def setup_goalset(goalset)
		goalset.goals.build
		goalset
	end

end

app/views/goal_sets/_calendar.html.haml
%div{:id=>"calendar"}
	= calendar @goalsets do |goal_set| 
		%div{:class=>"vertical"} 
			= progress_bar(goals_complete_percentage(goal_set.completed_goals, goal_set.goals.length), :color => 'green', :rounded=>true, :tiny=>true)  
	= link_to "Start fresh...", {:controller=>"goal_sets", :action=>"destroy_all_goalsets"}, 
		:method=>:post, :remote=>true,  :confirm=>"This will remove all Goals, past and present."

app/views/goal_sets/_dated_goalset.html.haml
- @current_goalsets.each do |dated_goalset|
	%div{:id=>"goalset-container", :class=>"box"}
		= link_to image_tag("cross.png"), {:controller=>"goal_sets", :action=>"destroy", :id=>dated_goalset}, 
			:method=>:post, :remote=>true,  :method => :delete,  :class=>"destroy_goalset"

		%h1 Goals for #{link_to dated_goalset.start_time_readable, edit_goal_set_path(dated_goalset), :remote=>true}
		= progress_bar(goals_complete_percentage(dated_goalset.completed_goals, dated_goalset.goals.length), :color => 'green', :rounded=>true) 
		
		%br
		%ul
			- dated_goalset.goals.each do |goal| 
				%li
					- if goal.complete?
						= link_to image_tag("tick.png"), {:controller=>"goal_sets", :action=>"toggle_complete", :id=>goal},
							 :method=>:post,:remote => true , :id => "complete_link_#{goal.id}" 
					- else
						= link_to image_tag("marquee.png"), {:controller=>"goal_sets", :action=>"toggle_complete", :id=>goal},
							 :method=>:post, :remote => true , :id => "complete_link_#{goal.id}" 

					%div{:class=>"content"}= goal.content
					%div{:class=>"controls"}
						= link_to image_tag("compose.png"), edit_goal_set_path(dated_goalset), :remote => true 
						= link_to image_tag("cross.png"), {:controller=>"goal_sets", :action=>"destroy_goal", :id=>goal}, 
							:method=>:post, :remote=>true,  :method => :delete

app/views/goal_sets/_edit_form.html.haml
%div{:id=>"flash_notice", :style=>"display:none"}
%h4 Editing GoalSet
%div{:id=>"goals-form"}
	= form_for @goalset, :as=>:goalset, :remote => true do |f|
		= f.date_select :start_time, :order=>[:day, :month], :discard_year=>true

		-if @goalset.errors.any?
			%div{:id=>"post_errors"}
				%h2= "#{pluralize(@goalset.errors.count, "error")} Errors"
				%ul
					- @goalset.errors.full.message.each do |msg|
						%li= msg
		= f.fields_for :goals do |ff|
			%span{:class=>"field"}
				= ff.text_field :content, :class=>"content-input-field"
		= link_to image_tag("plus.png"), {:controller=>"goal_sets", :action=>"add_goal"}, 
			:method=>:post, :remote=>true, :id=>@goalset, :class=>"new-goal-button"
		%span{:class=>"field"}= f.submit

app/views/goal_sets/_efficiency.html.haml
%h1 Overall Efficiency
= progress_bar(goals_complete_percentage(@completed_goal_count, @total_goal_count), :color => 'purple', :rounded=>true) 
= render :partial=>"calendar"

	

app/views/goal_sets/_form.html.haml
%div{:id=>"flash_notice", :style=>"display:none"}
%h4 Goals
%div{:id=>"goals-form"}
	= form_for setup_goalset(@goalset), :as=>:goalset, :remote => true do |f|
		-if @goalset.errors.any?
			%div{:id=>"goalset_errors"}
				%h2= "#{pluralize(@goalset.errors.count, "error")} Errors"
				%ul
					- @goalset.errors.full.message.each do |msg|
						%li= msg
		= f.date_select :start_time, :order=>[:day, :month], :discard_year=>true
		= f.fields_for :goals do |ff|
			%span{:class=>"field"}
				= ff.text_field :content, :class=>"content-input-field"
		%span{:class=>"field"}= f.submit

app/views/goal_sets/add_goal.js.erb
$("#goals-form").html("<%= escape_javascript(render(:partial => "edit_form"))%>");

app/views/goal_sets/create.js.erb
<% if @goalset.errors.any? -%>
 	$("#flash_notice").hide(300);
	$("#goalset_errors").html("<%= escape_javascript(error_messages_for(@goalset))%>");
	$("#goalset_errors").show(300);
<% else -%>
	$("#goals-form").html("<%= escape_javascript(render(:partial => "form"))%>");
	$("#goalset-section").html("<%= escape_javascript( render(:partial => "dated_goalset") ) %>");
	$("#efficiency-section").html("<%= escape_javascript( render(:partial => "efficiency") ) %>");
<% end -%>

app/views/goal_sets/destroy.js.erb
$("#efficiency-section").html("<%= escape_javascript( render(:partial => "efficiency") ) %>");
$("#goalset-section").html("<%= escape_javascript( render(:partial => "dated_goalset") ) %>");

app/views/goal_sets/destroy_all_goalsets.js.erb
$("#efficiency-section").html("<%= escape_javascript( render(:partial => "efficiency") ) %>");
$("#goalset-section").html("<%= escape_javascript( render(:partial => "dated_goalset") ) %>");

app/views/goal_sets/destroy_goal.js.erb
$("#efficiency-section").html("<%= escape_javascript( render(:partial => "efficiency") ) %>");
$("#goalset-section").html("<%= escape_javascript( render(:partial => "dated_goalset") ) %>");

app/views/goal_sets/edit.js.erb
$("#goals-form").html("<%= escape_javascript(render(:partial => "edit_form"))%>");

app/views/goal_sets/index.html.haml
%div{:class=>"row"}
	%div{:class=>"col feature"}
		%div{:id=>"efficiency-section", :class=>"box"}
			= render :partial => 'efficiency'
	%div{:class=>"col feature"}
		%div{:id=>"goalset-section"}
			=render :partial => 'dated_goalset'
	%div{:class=>"col feature"}
		%div{:id=>"goals-form", :class=>"box"}
			%div{:id=>"goalset_errors"}
			= render :partial=>"form" 

app/views/goal_sets/toggle_complete.js.erb
$("#efficiency-section").html("<%= escape_javascript( render(:partial => "efficiency") ) %>");
$("#goalset-section").html("<%= escape_javascript( render(:partial => "dated_goalset") ) %>");

app/views/goal_sets/update.js.erb
<% if @goalset.errors.any? -%>
  $("#flash_notice").hide(300);
  $("#flash_notice").html("<%= escape_javascript(error_messages_for(@goalset))%>");
  $("#flash_notice").show(300);
<% else -%>
  $("#goals-form").html("<%= escape_javascript(render(:partial => "form"))%>");
  $("#efficiency-section").html("<%= escape_javascript( render(:partial => "efficiency") ) %>");
  $("#goalset-section").html("<%= escape_javascript( render(:partial => "dated_goalset") ) %>");
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Get Your Shit Together</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>

	<%= yield %>
</body>
</html>